clear all
//Young dependency ratio
import excel "C:\Users\daves\OneDrive\Pessoal\Acadêmico\Mestrado\Dissertação - Execução\Dissertação\Quadros e gráficos\Table 11.xlsx", sheet("Planilha2") firstrow
xtset Code Year

///Gráficos
twoway (lfit Percentagechange Year if Region == "Água Boa", lcolor(green) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Alta Floresta", lcolor(green) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Barra do Garças", lcolor(blue) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Cáceres", lcolor(blue) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Confresa - Vila Rica", lcolor(red) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Cuiabá", lcolor(red) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Diamantino", lcolor(black) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Jaciara", lcolor(black) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Juara", lcolor(yellow) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Juína", lcolor(yellow) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Mirassol D'oeste", lcolor(orange) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Peixoto de Azevedo - Guarantã do Norte", lcolor(orange) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Ponteslç e Lacerda - Comodoro", lcolor(purple) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Primavera do Leste", lcolor(purple) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Rondonópolis", lcolor(gs10) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Sinop", lcolor(gs10) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Sorriso", lcolor(brown) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Tangará da Serra", lcolor(brown) lpattern(longdash) lwidth(thick)) , legend(order(1 "Água Boa" 2 "Alta Floresta" 3 "Barra Garças" 4 "Cáceres" 5 "Confresa" 6 "Cuiabá" 7 "Diamantino" 8 "Jaciara" 9 "Juara" 10 "Juína" 11 "Mirassol" 12 "Peixoto de Azevedo" 13 "Pontes e Lacerda" 14 "Primavera do Leste" 15 "Rondonópolis" 16 "Sinop" 17 "Sorriso" 18 "Tangará da Serra")) legend(size(*0.4)) legend(cols(6)) ylabel(#20) ylabel(, angle(0)) yline(0, lcolor(black) lpattern(line) lwidth(thin))
//exportar para jpg
graph export "C:/Users/daves/OneDrive/Pessoal/Acadêmico/Mestrado/Dissertação - Execução/Dissertação/Quadros e gráficos/Graph3.jpg", as(jpg) replace width(4000) height(3000)

clear all

//Elderely dependency ratio
import excel "C:\Users\daves\OneDrive\Pessoal\Acadêmico\Mestrado\Dissertação - Execução\Dissertação\Quadros e gráficos\Table 12.xlsx", sheet("Planilha2") firstrow
xtset Code Year

///Gráficos
twoway (lfit Percentagechange Year if Region == "Água Boa", lcolor(green) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Alta Floresta", lcolor(green) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Barra do Garças", lcolor(blue) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Cáceres", lcolor(blue) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Confresa - Vila Rica", lcolor(red) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Cuiabá", lcolor(red) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Diamantino", lcolor(black) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Jaciara", lcolor(black) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Juara", lcolor(yellow) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Juína", lcolor(yellow) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Mirassol D'oeste", lcolor(orange) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Peixoto de Azevedo - Guarantã do Norte", lcolor(orange) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Ponteslç e Lacerda - Comodoro", lcolor(purple) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Primavera do Leste", lcolor(purple) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Rondonópolis", lcolor(gs10) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Sinop", lcolor(gs10) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Sorriso", lcolor(brown) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Tangará da Serra", lcolor(brown) lpattern(longdash) lwidth(thick)) , legend(order(1 "Água Boa" 2 "Alta Floresta" 3 "Barra Garças" 4 "Cáceres" 5 "Confresa" 6 "Cuiabá" 7 "Diamantino" 8 "Jaciara" 9 "Juara" 10 "Juína" 11 "Mirassol" 12 "Peixoto de Azevedo" 13 "Pontes e Lacerda" 14 "Primavera do Leste" 15 "Rondonópolis" 16 "Sinop" 17 "Sorriso" 18 "Tangará da Serra")) legend(size(*0.4)) legend(cols(6)) ylabel(#20) ylabel(, angle(0))
//exportar para jpg
graph export "C:/Users/daves/OneDrive/Pessoal/Acadêmico/Mestrado/Dissertação - Execução/Dissertação/Quadros e gráficos/Graph4.jpg", as(jpg) replace width(4000) height(3000)


clear all

//Total dependency ratio
import excel "C:\Users\daves\OneDrive\Pessoal\Acadêmico\Mestrado\Dissertação - Execução\Dissertação\Quadros e gráficos\Table 13.xlsx", sheet("Planilha2") firstrow
xtset Code Year

///Gráficos
twoway (lfit Percentagechange Year if Region == "Água Boa", lcolor(green) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Alta Floresta", lcolor(green) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Barra do Garças", lcolor(blue) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Cáceres", lcolor(blue) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Confresa - Vila Rica", lcolor(red) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Cuiabá", lcolor(red) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Diamantino", lcolor(black) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Jaciara", lcolor(black) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Juara", lcolor(yellow) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Juína", lcolor(yellow) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Mirassol D'oeste", lcolor(orange) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Peixoto de Azevedo - Guarantã do Norte", lcolor(orange) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Ponteslç e Lacerda - Comodoro", lcolor(purple) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Primavera do Leste", lcolor(purple) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Rondonópolis", lcolor(gs10) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Sinop", lcolor(gs10) lpattern(longdash) lwidth(thick)) (lfit Percentagechange Year if Region == "Sorriso", lcolor(brown) lpattern(line) lwidth(thick)) (lfit Percentagechange Year if Region == "Tangará da Serra", lcolor(brown) lpattern(longdash) lwidth(thick)) , legend(order(1 "Água Boa" 2 "Alta Floresta" 3 "Barra Garças" 4 "Cáceres" 5 "Confresa" 6 "Cuiabá" 7 "Diamantino" 8 "Jaciara" 9 "Juara" 10 "Juína" 11 "Mirassol" 12 "Peixoto de Azevedo" 13 "Pontes e Lacerda" 14 "Primavera do Leste" 15 "Rondonópolis" 16 "Sinop" 17 "Sorriso" 18 "Tangará da Serra")) legend(size(*0.4)) legend(cols(6)) ylabel(#10, angle(45))
//exportar para jpg
graph export "C:/Users/daves/OneDrive/Pessoal/Acadêmico/Mestrado/Dissertação - Execução/Dissertação/Quadros e gráficos/Graph5.jpg", as(jpg) replace width(4000) height(3000)

